

exports.genMainPage = function () {
	pagHTML = `
	<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8"/>
			<title>TPC3 - Índice</title>
			<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
		</head>
		<body>
			<div class="w3-card">
				<header class="w3-container w3-blue-grey w3-xlarge">
					<p>Índice</p>
				</header>	

				<ul class="w3-ul w3-large w3-hoverable">
					<li class="w3-padding-medium">
						Lista de Pessoas 
					</li>
					<li class="w3-padding-medium"> 
						Lista de Pessoas Ordenadas
					</li>
					<li class="w3-padding-medium">
						Distribuição por Sexo
					</li>
					<li class="w3-padding-medium">
						Distribuição por Desporto
					</li>
					<li class="w3-padding-medium">
						Top 10 Profissões
					</li>
				</ul>
			</div>
		</body>
	</html>
	`

	return pagHTML
}

exports.genListPage = function (lista, sort) {
	pagHTML = `
	<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8"/>
			<title>TPC3 - Lista de Pessoas</title>
			<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
		</head>
		<body>
			<div class="w3-card">
				<header class="w3-container w3-deep-purple w3-xlarge">
					<h1>Lista de Pessoas${(sort) ?" Ordenada" :""}</h1>
				</header>	

				<table class="w3-table-all w3-hoverable">
					<tr>
						<th>Id</th>
						<th>Nome</th>
						<th>Idade</th>
						<th>Sexo</th>
						<th>Cidade</th>
					</tr>`

	if (sort) {
		lista.sort( (p1, p2) => (p1.nome < p2.nome) ?-1 :1)
	}

	for (let i=0 ; i<lista.length ; i++)
	{
		let pessoa = lista[i]

		pagHTML += `
						<tr>
							<td>${pessoa.id}</td>
							<td>${pessoa.nome}</td>
							<td>${pessoa.idade}</td>
							<td>${pessoa.sexo}</td>
							<td>${pessoa.morada.cidade}</td>
						</tr>
		`
	}

	pagHTML += `
				</table>

				<footer class="w3-container w3-deep-purple">
					<h5>Generated by the server</h5>
				</footer>

			</div>
		</body>
	</html>
	`
	return pagHTML
}

exports.genListByGender = function (lista) 
{
	let numMasc = 0
	let numOutro = 0
	let numFem = 0

	for (let i=0 ; i<lista.length ; i++)
	{
		if (lista[i].sexo == "masculino")
		{
			numMasc++
		}
		else if (lista[i].sexo == "outro")
		{
			numOutro++
		}
		else if (lista[i].sexo == "feminino")
		{
			numFem++
		}
	}

	pagHTML = `
	<!DOCTYPE html>
	<html>
		<head>
			<meta charset="utf-8"/>
			<title>TPC3 - Distribuição por Sexo</title>
			<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>
		</head>
		<body>
			<div class="w3-card">
				<header class="w3-container w3-deep-purple w3-xlarge">
					<h1>Distribuição por Sexo</h1>
				</header>	

				<table class="w3-table-all w3-hoverable">
					<tr>
						<th>Sexo</th>
						<th>Número de Pessoas</th>
					</tr>
					<tr>
						<td>Masculino</td>
						<td>
							<a href="http://localhost:12345/pessoas?sexo=masculino">
								${numMasc}
							</a>
						</td>
					</tr>
					<tr>
						<td>Feminino</td>
						<td>
							<a href="http://localhost:12345/pessoas?sexo=feminino">
								${numFem}
							</a>
						</td>
					</tr>
					<tr>
						<td>Outro</td>
						<td>
							<a href="http://localhost:12345/pessoas?sexo=outro">
								${numOutro}
							</a>
						</td>
					</tr>
				</table>

				<footer class="w3-container w3-deep-purple">
					<h5>Generated by the server</h5>
				</footer>

			</div>
		</body>
	</html>
	`
	return pagHTML
}


exports.genSportsPage = function(lista)
{
	var dist = {}
	
	for (let i = 0 ; i<lista.length ; i++)
	{
		let pessoa = lista[i]
		for (let j=0 ; j<pessoa.desportos.length ; j++)
		{
			let desporto = pessoa.desportos[j]
			if (dist[desporto] == undefined)
			{
				dist[desporto] = 0
			}
			dist[desporto]++
		}
	}

	return "<p>" + JSON.stringify(dist) + "</p>"
}
